### ISSUE TITLE
Incorrect delaboration of antiquotations with functions that don't reduce

### ISSUE THREAD

**Issue by Vtec234** [gebner/quote4#18]
```lean
open Lean Qq

def foo (u : Level) (T : Q(Sort u)) : Q($T) → Q($T) := id
opaque bar (u : Level) : Q(Sort u) → Q(Sort u) := id

/- foo levelOne (bar levelOne q(ℕ)) : Q(bar) → Q(bar) -/
#check foo levelOne (bar levelOne q(Nat))

@[irreducible]
def baz (u : Level) : Q(Sort u) → Q(Sort u) := id

/- foo levelOne (baz levelOne q(ℕ)) : Q(baz) → Q(baz) -/
#check foo levelOne (baz levelOne q(Nat))
```

**Comment by Vtec234** [comment]
Apologies for not stating the expected result. `Q(bar)` cannot possibly be correct since `bar` is not a sort. If substitution worked under antiquotations, I would expect `foo levelOne (bar levelOne q(Nat)) : Q($(bar levelOne q(Nat))) -> Q($(bar levelOne q(Nat)))`, or some variant of that which tries to be more clever in delaborating the contents of `$(..)`. In lieu of that, perhaps even just `Q(<failed to print>)` might be better than `Q(bar)`.

**Comment by gebner** [comment]
Now I understand what you mean.  Maybe reusing the name wasn't such a great decision after all.  If you hover over `bar`, you'll see that it has type `Type` so everything works out.  It's just that `bar` should actually be named `$(bar ....)` (but I'm not sure how to pretty-print that).

**Comment by gebner** [comment]
It now prints:
```lean
foo levelOne (baz levelOne q(Nat)) : (let baz_1 := baz levelOne q(Nat);
  Q(«$baz_1»)) →
  let baz_1 := baz levelOne q(Nat);
  Q(«$baz_1»)
```

BTW, there's now level quotations as well.  You can write `ql(1)` instead of `levelOne`.
