### ISSUE TITLE
error: unknown identifier 'resettingSynthInstanceCache' on Lean nightly with fresh package.

### ISSUE THREAD

**Issue by debordle** [gebner/quote4#7]
I'm getting this error output when building a brand new mostly blank package:

`Building Qq.Macro
error: > LEAN_PATH=./lake-packages/mathlib/build/lib:./lake-packages/Qq/build/lib:./lake-packages/aesop/build/lib:./build/lib:./lake-packages/std/build/lib LD_LIBRARY_PATH=/home/deb/.elan/toolchains/leanprover--lean4---nightly/lib:./lake-packages/Qq/build/lib /home/deb/.elan/toolchains/leanprover--lean4---nightly/bin/lean ./lake-packages/Qq/././Qq/Macro.lean -R ./lake-packages/Qq/./. -o ./lake-packages/Qq/build/lib/Qq/Macro.olean -i ./lake-packages/Qq/build/lib/Qq/Macro.ilean -c ./lake-packages/Qq/build/ir/Qq/Macro.c
error: stdout:
./lake-packages/Qq/././Qq/Macro.lean:377:8: error: unknown identifier 'resettingSynthInstanceCache'
error: external command ``/home/deb/.elan/toolchains/leanprover--lean4---nightly/bin/lean`` exited with code 1`

Steps to get this error, for me:

1. Create new project with `lake new package math`
2. Add `import Mathlib.Data.Real.Basic` to Package.lean.
3. Update `lean-toolchain` to `leanprover/lean4:nightly`
4. Run `elan update`, `lake update` then `lake build`.

**Comment by gebner** [comment]
> Update `lean-toolchain` to `leanprover/lean4:nightly`

You should *never* do that.  Please just copy `lake-packages/mathlib/lean-toolchain` to `lean-toolchain`.

> Run `elan update`, `lake update`

You should not do that either.  And always copy `lake-packages/mathlib/lean-toolchain` to `lean-toolchain` *after* running `lake update`.  Only call `lake update` if you want a new mathlib version.
